[ req ]
default_bits       = 4096
distinguished_name = dn
req_extensions     = v3_req
prompt             = no
default_md         = sha256
[ dn ]          # Distinguished Name (Nom de domaine)
CN = IBTN-PCF-069.ibtn.local
[ v3_req ]
keyUsage = keyEncipherment, dataEncipherment
subjectAltName = @alt_names
extendedKeyUsage = serverAuth
[ alt_names ]   # Subject Alternative Names (Noms alternatifs)
                # Pour les DNS et la machine (IP)
DNS.1 = IBTN-PCF-069
DNS.2 = IBTN-PCF-069.ibtn.local
IP.1  = 192.168.50.247
